services:
    model-server-capybara:
      image: ghcr.io/abetlen/llama-cpp-python:latest
      ports:
      - "9081:8001"

      volumes:
        - /home/bateiko/Projects/publication/chatbot-evaluation/models:/models

      environment:
        - MODEL=/models/capybarahermes-2.5-mistral-7b.Q2_K.gguf, /models/capybarahermes-2.5-mistral-7b.Q2_K.gguf
        - API_KEY=key
        - CHAT_FORMAT=chatml
        - PORT=8001
#        - SYSTEM_PROMPT_FILE=

    model-server-mistral:
      image: ghcr.io/abetlen/llama-cpp-python:latest
      ports:
      - "9091:8001"

      volumes:
        - /home/bateiko/Projects/publication/chatbot-evaluation/models:/models

      environment:
        - MODEL=/models/mistral-7b-v0.1.Q2_K.gguf
        - API_KEY=key
        - CHAT_FORMAT=chatml
        - PORT=8001
