services:
    model-server-capybara:
      image: ghcr.io/abetlen/llama-cpp-python:latest
      ports:
        - "9081:8001"

      volumes:
        - /home/bateiko/Projects/publication/chatbot-evaluation/models:/models

      environment:
        - MODEL=/models/capybarahermes-2.5-mistral-7b.Q2_K.gguf
        - API_KEY=key
        - CHAT_FORMAT=chatml
        - PORT=8001
##        - SYSTEM_PROMPT_FILE=

    web-app:
      build:
        context: .
        dockerfile: Dockerfile

      ports:
          - "9090:8080"
      environment:
        - MODEL_URL=http://model-server-capybara:8001/v1
        - MODEL_NAME=/models/mistral-7b-v0.1.Q2_K.gguf
        - API_KEY=key
        - PORT=8080
        - HOST=0.0.0.0
        - MINIO_ENDPOINT=minio:9000
        - MINIO_ROOT_USER=user1111
        - MINIO_ROOT_PASSWORD=user1111
        - MINIO_BUCKET=logging
      depends_on:
        - model-server-capybara
        - minio
      volumes:
        - /home/bateiko/Projects/publication/chatbot-evaluation/loggs:/app/loggs
      command: python3 src/gradio_app.py

    minio:
     image: minio/minio:latest
     command: server --console-address ":9001" /data/ --address 0.0.0.0:9000
     ports:
       - "9010:9000"
       - "9001:9001"
     environment:
       MINIO_ROOT_USER: user1111
       MINIO_ROOT_PASSWORD: user1111
     volumes:
       - minio-storage:/data
     healthcheck:
       test: ["CMD", "curl", "-f", "http://0.0.0.0:9000/minio/health/live"]
       interval: 30s
       timeout: 20s
       retries: 3

volumes:
 minio-storage:
