services:
    model-server-capybara:
      image: ghcr.io/abetlen/llama-cpp-python:latest
      ports:
        - "9081:8001"

      volumes:
        - /home/bateiko/Projects/publication/chatbot-evaluation/models:/models

      environment:
        - MODEL=${MODEL_NAME}
        - API_KEY=${API_KEY}
        - CHAT_FORMAT=chatml
        - PORT=8001

    web-app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
          - "9090:8080"
      environment:
        - MODEL_URL=http://model-server-capybara:8001/v1
        - MODEL_NAME=${MODEL_NAME}
        - API_KEY=${API_KEY}
        - PORT=8080
        - HOST=0.0.0.0
        - MINIO_ENDPOINT=minio:9000
        - MINIO_ROOT_USER=${MINIO_ROOT_USER}
        - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        - MINIO_BUCKET=${MINIO_BUCKET}
      depends_on:
        - model-server-capybara
        - minio
      command: python3 src/gradio_app.py

    minio:
     image: minio/minio:latest
     command: server --console-address ":9001" /data/ --address 0.0.0.0:9000
     ports:
       - "9010:9000"
       - "9001:9001"
     environment:
       MINIO_ROOT_USER: ${MINIO_ROOT_USER}
       MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
     volumes:
       - minio-storage:/data
     healthcheck:
       test: ["CMD", "curl", "-f", "http://0.0.0.0:9000/minio/health/live"]
       interval: 30s
       timeout: 20s
       retries: 3

volumes:
 minio-storage:
